### ISSUE TITLE
Incoming messages are not updated in real time

### ISSUE THREAD

**Issue by anup-dh** [shridarpatil/whatsapp_chat#5]
For all incoming messages we need to refresh browser window to see messages.

**Comment by shridarpatil** [comment]
this is fixed

**Comment by anup-dh** [comment]
Still not working @shridarpatil 

when ever customer messgages, neither the chat window shows new messages, not message counter updates at top until browser refresh.
